#!/bin/bash

#
# Eclipse P2 mirroring script
#
# (c) 2013 Gerrit Beine <gerrit.beine@gmx.de>
#
# See
# http://wiki.eclipse.org/Equinox_p2_Repository_Mirroring
# http://wiki.eclipse.org/Eclipse_Project_Update_Sites
#

# Specify path to Eclipse executable
eclipse="/opt/eclipse/eclipse"

# Mirror repository metadata
function mirror_metadata()
{
    local source=$1
    local target=$2
    run_p2 ${source} ${target} "org.eclipse.equinox.p2.metadata.repository.mirrorApplication"
}

# Mirror repository content
function mirror_artifacts()
{
    local source=$1
    local target=$2
    run_p2 ${source} ${target} "org.eclipse.equinox.p2.artifact.repository.mirrorApplication"
}

# Execute Eclipse mirror
function run_p2()
{
    local source=$1
    local target=$2
    local application=$3
    local options=$4
    echo
    echo
    echo "--------------------------------------------------------------------------------"
    echo
    echo "Mirroring ${source}"
    echo
    ${eclipse} -nosplash -verbose \
        -application ${application} \
        -source ${source} \
        -destination ${target}
    echo
    echo "--------------------------------------------------------------------------------"
    echo
}

function run_mirror()
{
    local source=$1
    local target=$2
    local application=org.eclipse.update.core.standaloneUpdate
    echo
    echo
    echo "--------------------------------------------------------------------------------"
    echo
    echo "Mirroring ${source}"
    echo
    ${eclipse} -nosplash -verbose \
        -application ${application} \
        -command mirror \
        -from ${source} \
        -to ${target}
    echo
    echo "--------------------------------------------------------------------------------"
    echo

}

target=$1

if [ ! -d ${target} ]; then
    echo "Specificy target directory"
    exit 1
fi

while read LINE; do
    if [[ -z ${LINE} || "${LINE}" == "#"* ]]; then
        continue
    fi
    p2=${LINE%%;*}
    LINE=${LINE##*;}
    SOURCE=${LINE%%#>>#*}
    TARGET=${LINE##*#>>#}
    if [[ "${p2}" == "mirror" ]]; then
        run_mirror ${SOURCE} "${target}/${TARGET}"
    else
        mirror_metadata ${SOURCE} "${target}/${TARGET}"
        mirror_artifacts ${SOURCE} "${target}/${TARGET}"
    fi
done < eclipse-update-sites.map

