#!/bin/sh

site=$1
dropins=$2

cd $1

for f in `ls features`; do
  feature=${f%%.jar}
  echo $feature
  path=$dropins/features/$feature
  mkdir $path
  (cd $path && unzip $site/features/$f)
done

for p in `ls plugins`; do
  path=$dropins/plugins
  cp $site/plugins/$p $path
done

