#!/bin/bash

####################################
# Tear Down Ethernet bridge on Linux
####################################

# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged together
tap="tap0"

gw="192.168.0.254"

echo "Removing bridge $br"
/sbin/ifconfig $br down
/sbin/brctl delbr $br

for t in $tap; do
    echo "Removing tunnel device $t"
    /usr/sbin/openvpn --rmtun --dev $t
done

echo "Setting default gateway to $eth_gw"
/sbin/route add default gw $gw
