#!/bin/bash

CASK=/opt/homebrew-cask/Caskroom

if [ -n "$1" -a "-f" = "$1" ]; then
  DO_UPGRADE=true
fi

for cask in `ls $CASK`; do
  ver=`brew cask info $cask | grep ^$cask:`
  version=${ver##* }
  if [ ! -d ${CASK}/${cask}/${version} ]; then
    if [ ${DO_UPGRADE} ]; then
      echo "Upgrading ${cask} to ${ver}"
      brew cask uninstall --force ${cask}
      brew cask install ${cask}
    else
      echo "New version of ${cask}: ${ver}"
    fi
  fi
done
