#! /bin/sh
#
# $Id: mksmtpdcert.in,v 1.4 2001/08/26 15:49:50 mrsam Exp $
#
# Copyright 2000 Double Precision, Inc.  See COPYING for
# distribution information.
#
# This is a short script to quickly generate a self-signed X.509 key for
# SMTP over SSL.  Normally this script would get called by an automatic
# package installation routine.
#

test -x /usr/bin/openssl || exit 0

prefix="/usr/local"

if test -f /usr/local/share/smtpd.pem
then
	echo "/usr/local/share/smtpd.pem already exists."
	exit 1
fi

cp /dev/null /usr/local/share/smtpd.pem
chmod 600 /usr/local/share/smtpd.pem
chown root /usr/local/share/smtpd.pem

cleanup() {
	rm -f /usr/local/share/smtpd.pem
	rm -f /usr/local/share/smtpd.rand
	exit 1
}

cd /usr/local/share
dd if=/dev/urandom of=/usr/local/share/smtpd.rand count=1 2>/dev/null
/usr/bin/openssl req -new -x509 -days 365 -nodes \
	-config /usr/local/etc/smtpd.cnf -out /usr/local/share/smtpd.pem -keyout /usr/local/share/smtpd.pem || cleanup
/usr/bin/openssl gendh -rand /usr/local/share/smtpd.rand 512 >>/usr/local/share/smtpd.pem || cleanup
/usr/bin/openssl x509 -subject -dates -fingerprint -noout -in /usr/local/share/smtpd.pem || cleanup
rm -f /usr/local/share/smtpd.rand
